// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables, fallback to current constants for local/dev so the app still runs
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://keaussqpmjddixekhcpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYXVzc3FwbWpkZGl4ZWtoY3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzU2ODAsImV4cCI6MjA3MDQxMTY4MH0.igKyWT-iKl8xlE_GPLXPDmz21-VorRnTvnlWv98nhGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});